language: generic

#fail_fast: true

#install: sudo apt-get install clang gcc

#compiler:
#    - clang
#    - gcc

script: make travis

notifications:
    irc: "chat.freenode.net#contauto"
    email: false

